spring:
    application:
        name: rays-gate
server:
    port: 8766 #启动端口

eureka:
    client:
        serviceUrl:
            defaultZone: http://localhost:8761/eureka/
#
zuul:
  ignored-services: "*"
  sensitive-headers:
  prefix: /api #为zuul设置一个公共的前缀
#  ratelimit: # 网关限流
#    key-prefix: gate_rate
#    enabled: true
#    repository: REDIS #REDIS, JPA, IN_MEMORY
#    behind-proxy: true
#    default-policy: #optional - will apply unless specific policy exists
#      limit: 200
#      refresh-interval: 60 #default value (in seconds)
#      type: #optional
#        - user
#        - origin
#        - url
  routes:
    resource:
      path: /resource/**
      serviceId: rays-resource

    auth:
      path: /auth/**
      serviceId: rays-auth

    web:
      path: /web/**
      serviceId: rays-web

ribbon:
  eureka:
    enabled: true